---
- name: install and configure elasticsearch
  hosts: elastic_srv
  become: true

  tasks:
    - name: install elasticsearch
      apt:
        deb: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/e/elasticsearch/elasticsearch-7.15.1-amd64.deb"
    
    - name: configure elasticsearch
      template:
        src: ./elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml

    - name: daemon reload
      systemd:
        daemon_reload: true
    
    - name: restart elasticsearch and enable
      service:
        name: elasticsearch
        enabled: true
        state: restarted